FROM node:16-bullseye as NODE_BUILD
ENV MAKEFLAGS="-j8"
RUN echo $MAKEFLAGS
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y git build-essential linux-headers-amd64 make python

# install libsass
RUN git clone https://github.com/sass/sassc && cd sassc && \
    git clone https://github.com/sass/libsass && \
    SASS_LIBSASS_PATH=/sassc/libsass make -j$(nproc) && \
    mv bin/sassc /usr/bin/sassc && \
    cd ../ && rm -rf /sassc

# created node-sass binary
ENV SASS_BINARY_PATH=/usr/lib/node_modules/node-sass/build/Release/binding.node
RUN git clone --recursive https://github.com/sass/node-sass.git && \
    cd node-sass && \
    git checkout v4.14.1 && \
    git submodule update --init --recursive && \
    CXXFLAGS="--std=c++17" npm install && \
    CXXFLAGS="--std=c++17" node scripts/build -f && \
    cd ../ && rm -rf node-sass

# add binary path of node-sass to .npmrc
RUN touch $HOME/.npmrc && echo "sass_binary_cache=${SASS_BINARY_PATH}" >> $HOME/.npmrc

ENV SKIP_SASS_BINARY_DOWNLOAD_FOR_CI true
ENV SKIP_NODE_SASS_TESTS true

WORKDIR /go/src/github.com/88250/pipe/
USER 1000
RUN cd console && yarn --registry https://registry.npm.taobao.org install && cd ../theme && yarn --registry https://registry.npm.taobao.org install

ENV TZ=Asia/Shanghai
EXPOSE 5897
