FROM golang:1-bullseye as GO_BUILD
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y build-essential git
ENV GO111MODULE=on
WORKDIR /go/src/github.com/88250/pipe/
RUN go install github.com/codegangsta/gin && go build -i -v
